### ISSUE TITLE
Serials not changing

### ISSUE THREAD

**Issue by mattplayys** [StHomeLess/HWID-Kernel-Spoofer#4]
My serials aren't changing. they do pop up twice when i run the spoofer so i assume that they are supposed to be changed however after running the spoofer they don't change
![Screenshot (3)](https://user-images.githubusercontent.com/91571045/147723336-b2395b96-4c22-4ada-bb1b-ef98206127b7.png)
![Screenshot (4)](https://user-images.githubusercontent.com/91571045/147723338-02ca6563-4585-4693-89ae-d2af235860ad.png)
.

**Comment by mattplayys** [comment]
i left a before and after pic of my serials and a screenshot of the part i mentioned

**Comment by StHomeLess** [comment]
maybe your windows version
